### ISSUE TITLE
YAMLLoadWarning Error

### ISSUE THREAD

**Issue by f4depo** [valeriobasile/twittercrawler#3]
I've installed everything purely but my code doesn't working. Here's my output; 

```
crawl.py:11: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(fd_conf)
retrieving tweets for screen name: xxxxxxxxxxx
error parsing tweet
error parsing tweet
error parsing tweet
error parsing tweet
error parsing tweet
error parsing tweet
error parsing tweet
error parsing tweet
error parsing tweet
```
then i searched this error and change crawl.py's 11th line with this 

`   config = yaml.load(fd_conf, Loader=yaml.SafeLoader)`

that has solved my problem but still give "error parsing tweet" output.

**Comment by valeriobasile** [comment]
Thanks, I updated the line as you suggested (commit https://github.com/valeriobasile/twittercrawler/commit/9dabba8cdd09b5538624b3a7b73a7b647b8782e3)

Feel free to send a pull request in the future for fixes like this.

I also made the "error parsing tweet" more transparent by making it print the exception.
